### ISSUE TITLE
POM.xml Error

### ISSUE THREAD

**Issue by Yamuna-Rani** [vkirankumar3090/zephyrWithCucumber#4]
I have some issues in downloading the jar files.

Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JiraZapi 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] Downloading: https:packages.atlassian.com/mvn/maven-atlassian-snapshot-external/com/atlassian/fugue/fugue/3.0.0-m007/fugue-3.0.0-m007.pom
[INFO] Downloading: https://m2proxy.atlassian.com/repository/public/com/atlassian/fugue/fugue/3.0.0-m007/fugue-3.0.0-m007.pom
[INFO] Downloading: https://maven.atlassian.com/content/groups/public/com/atlassian/fugue/fugue/3.0.0-m007/fugue-3.0.0-m007.pom
[INFO] Downloading: https:packages.atlassian.com/mvn/maven-atlassian-snapshot-external/com/atlassian/jwt/jwt-api/1.6.2/jwt-api-1.6.2.pom
[INFO] Downloading: https://m2proxy.atlassian.com/repository/public/com/atlassian/jwt/jwt-api/1.6.2/jwt-api-1.6.2.pom
[INFO] Downloading: https://maven.atlassian.com/content/groups/public/com/atlassian/jwt/jwt-api/1.6.2/jwt-api-1.6.2.pom
[INFO] Downloading: https:packages.atlassian.com/mvn/maven-atlassian-snapshot-external/com/atlassian/connect/ac-play-java_2.10/0.10.1/ac-play-java_2.10-0.10.1.pom
[INFO] Downloading: https://m2proxy.atlassian.com/repository/public/com/atlassian/connect/ac-play-java_2.10/0.10.1/ac-play-java_2.10-0.10.1.pom
[INFO] Downloading: https://maven.atlassian.com/content/groups/public/com/atlassian/connect/ac-play-java_2.10/0.10.1/ac-play-java_2.10-0.10.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.253 s
[INFO] Finished at: 2019-07-15T14:52:52+05:30
[INFO] Final Memory: 8M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project JiraZapi: Could not resolve dependencies for project ZephyrWithCucumber:JiraZapi:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.atlassian.fugue:fugue:jar:3.0.0-m007: Failed to read artifact descriptor for com.atlassian.fugue:fugue:jar:3.0.0-m007: Could not transfer artifact com.atlassian.fugue:fugue:pom:3.0.0-m007 from/to atlassian-public1 (https:packages.atlassian.com/mvn/maven-atlassian-snapshot-external): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by vkirankumar3090** [comment]
@Yamuna-Rani  i'm able to rebuild the project successfully. looks like there is some security issue with your network please check that and try to fix it, because of that your seeing above issue.
"sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]"

**Comment by Yamuna-Rani** [comment]
Okay kiran. I will check that.

Thanks,
Yamuna Rani (UST, IND)
